version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Reza2025
    ports:
      - "1437:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped

volumes:
    sqlvolume: