// <auto-generated />
using System;
using ContractorDocuments.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractorDocuments.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240725123008_initializeTables")]
    partial class initializeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Customers.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Directory.MeasureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SystemKeyword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Measures", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Materials.MaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeasureId");

                    b.HasIndex("ParentMaterialId");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ConstructStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ProjectTypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("ConstructStages", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectContractEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(16,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SharePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.ToTable("ProjectContracts", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasMaxLength(15)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectTypeId")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConstructStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConstructStageId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectStages", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectStageMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalNetProfit")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectStepId");

                    b.ToTable("ProjectStageMaterials", (string)null);
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Customers.UserEntity", b =>
                {
                    b.OwnsOne("ContractorDocuments.Domain.ValueObjects.Fullname", "Fullname", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.Property<string>("Surname")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Surname");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.OwnsOne("ContractorDocuments.Domain.ValueObjects.PasswordHash", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Password");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Fullname")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Materials.MaterialEntity", b =>
                {
                    b.HasOne("ContractorDocuments.Domain.Entities.Directory.MeasureEntity", "Measure")
                        .WithMany("Materials")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractorDocuments.Domain.Entities.Materials.MaterialEntity", "ParentMaterial")
                        .WithMany("ChildrenMaterial")
                        .HasForeignKey("ParentMaterialId");

                    b.Navigation("Measure");

                    b.Navigation("ParentMaterial");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectEntity", b =>
                {
                    b.HasOne("ContractorDocuments.Domain.Entities.Projects.ProjectContractEntity", "Contract")
                        .WithOne("Project")
                        .HasForeignKey("ContractorDocuments.Domain.Entities.Projects.ProjectEntity", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectStageEntity", b =>
                {
                    b.HasOne("ContractorDocuments.Domain.Entities.Projects.ConstructStageEntity", "ConstructStage")
                        .WithMany("ProjectStages")
                        .HasForeignKey("ConstructStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractorDocuments.Domain.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("Stages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructStage");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectStageMaterialEntity", b =>
                {
                    b.HasOne("ContractorDocuments.Domain.Entities.Materials.MaterialEntity", "Material")
                        .WithMany("ProjectStageMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractorDocuments.Domain.Entities.Projects.ProjectStageEntity", "ProjectStep")
                        .WithMany("Materials")
                        .HasForeignKey("ProjectStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProjectStep");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Directory.MeasureEntity", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Materials.MaterialEntity", b =>
                {
                    b.Navigation("ChildrenMaterial");

                    b.Navigation("ProjectStageMaterials");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ConstructStageEntity", b =>
                {
                    b.Navigation("ProjectStages");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectContractEntity", b =>
                {
                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectEntity", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("ContractorDocuments.Domain.Entities.Projects.ProjectStageEntity", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
